name: NodeJS Pu

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Testing
        run: |
          npm install
          npm run test
  build:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Building..
        run: |
          echo "VERSION=$(cat package.json | jq .version)"
          npm install
          npm run build
      - name: Test
        run: |
          echo $VERSION
      - name: Prerelease
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest-${{ env.VERSION }}"
          prerelease: true
          title: "Development Build"
          files: |
            build/*.zip
